apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: team-b-app
  namespace: team-b
spec:
  host: team-b-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
